import Head from "next/head";
import styles from "../assets/styles/Home.module.css";
import Mailchimp from 'mailchimp-api-v3'

export async function getServerSideProps(_context) {
  // Pass data to the page via props
  console.log('<< Run >>')
  const mailchimp = new Mailchimp('');

  await mailchimp.get('/lists')
  .then(function (result) {
    console.log('result', result)
  })
  .catch(function (err) {
    console.log('err', err)
  })

  return {
    props: {
      title: "Kamezoko",
    },
  };
}

export default function Home({ title }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{title}</h1>

        <p className={styles.description}>
          Get started by editing{" "}
          <code className={styles.code}>pages/index.js</code>
        </p>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
